Add major new features: Brownies, floor plan, Docker image, improved tutorial, improved Android app; Many improvements and bug fixes

diff --git a/tools/home2l b/tools/home2l
--- a/tools/home2l
+++ b/tools/home2l
@@ -2,7 +2,7 @@
 
 # This file is part of the Home2L project.
 #
-# (C) 2015-2018 Gundolf Kiefer
+# (C) 2015-2020 Gundolf Kiefer
 #
 # Home2L is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -37,19 +37,26 @@ if [[ "$1" == "" ]]; then
   echo "  -e : show the full pathname of the environnment file and quit"
 else
 
-  # Guess installation directory and set environment...
-  HOME2L_ROOT=""
-  SELF=`realpath $0`
-  for DIR in ${SELF%/bin/*} $INSTALL_DIRS; do
-    ENV="$DIR/env.sh"
-    if [ -e "$ENV" ]; then
-      . $ENV
-      break
+  if [[ "$HOME2L_ROOT" != "" ]]; then
+    ENV="$HOME2L_ROOT/env.sh"
+    . $ENV
+  else
+
+    # Guess installation directory and set environment...
+    HOME2L_ROOT=""
+    SELF=`realpath $0`
+    for DIR in ${SELF%/bin/*} $INSTALL_DIRS; do
+      ENV="$DIR/env.sh"
+      if [ -e "$ENV" ]; then
+        . $ENV
+        break
+      fi
+    done
+    if [[ "$HOME2L_ROOT" == "" ]]; then
+      echo "ERROR: No Home2l installation found!"
+      exit 3
     fi
-  done
-  if [[ "$HOME2L_ROOT" == "" ]]; then
-    echo "ERROR: No Home2l installation found!"
-    exit 3
+
   fi
 
   # Execute command...
diff --git a/tools/home2l-adb b/tools/home2l-adb
--- a/tools/home2l-adb
+++ b/tools/home2l-adb
@@ -2,7 +2,7 @@
 
 # This file is part of the Home2L project.
 #
-# (C) 2015-2018 Gundolf Kiefer
+# (C) 2015-2020 Gundolf Kiefer
 #
 # Home2L is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -27,22 +27,35 @@
 #
 
 
-if [[ "$1" == "" ]]; then
+
+# Usage ...
+usage_and_exit () {
   echo "Usage: ${0##*/} <hostname> <adb command with args>"
   echo
   echo "Besides the usual adb commands, the following extended commands are supported:"
-  echo "  x-start <host>    : Start Home2L app on <host>"
-  echo "  x-stop <host>     : Stop Home2L app on <host>"
-  echo "  x-restart <host>"
-  echo "  x-reload <host>   : Restart Home2L app on <host>"
-  echo "  x-connect <host>  : (Re-)Connect Android host <host>"
+  echo "  x-start       : Start Home2L app"
+  echo "  x-stop        : Stop Home2L app"
+  echo "  x-restart     : Restart Home2L app"
+  echo
+  echo "  x-install-apk : (Re-)Install Home2L app"
+  echo "  x-install-etc : Update 'etc' for the Home2L app"
+  echo
+  echo "  x-ssh <host>  : Check SSH settings by starting a session on <host>"
+  echo "  x-connect     : (Re-)Connect Android host"
+  echo "  x-logcat      : Show Android logs for debugging"
   exit 3
+}
+
+if [[ "$1" == "" ]]; then
+  usage_and_exit
 fi
 
 #~ uname -a
 #~ echo $@
 
-# Determine coordinates of target device...
+
+
+# Determine coordinates of target device ...
 HOSTNAME=`hostname`
 DEV_NAME="$1"         # Given name (can be anything of hostname, device ID or port)
 
@@ -52,45 +65,114 @@ DEV_HOST=${REC[1]}    # (Host)name of the hosting machine, to which the Android 
 DEV_ID=${REC[2]}      # ADB device ID
 DEV_PORT=${REC[3]}    # Forwarding port
 
+
+
 # Re-run the script on the correct hosting machine...
 if [[ "$HOSTNAME" != "$DEV_HOST" ]]; then
   #~ echo HOSTNAME=-$HOSTNAME- DEV_HOST=-$DEV_HOST-
-  exec ssh -t $DEV_HOST home2l ${0##*-} $@
+  exec ssh -o LogLevel=QUIET -t home2l@$DEV_HOST home2l ${0##*-} $@
 fi
 
-# Determine actual command...
+
+
+# Invoke ADB with the desired device...
+run_adb () {
+  # Notes:
+  # - sg adb -c "adb -s $DEV_ID $CMD"  # does not work
+  # - The output of 'adb' should not be filtered (such as appending "sed 's#^#  [adb] #'"),
+  #   because otherwise, interaction is not possible and the TTY output gets scrambled.
+
+  #~ echo "### Running as '"`whoami`"': " adb -s $DEV_ID $@
+  if [[ "`whoami`" == "home2l" ]]; then
+    adb -s $DEV_ID $@
+  else
+    sudo -u home2l adb -s $DEV_ID $@
+  fi
+}
+
+
+
+# Execute actual command...
 shift
 CMD_START="am start org.home2l.app/.Home2lActivity"
 CMD_STOP="am force-stop org.home2l.app"
 case "$1" in
   x-stop)
     echo "Stopping Home2l app on $DEV_NAME ..."
-    CMD="shell $CMD_STOP"
+    run_adb "shell $CMD_STOP"
     ;;
   x-start)
     echo "Starting Home2l app on $DEV_NAME ..."
-    CMD="shell $CMD_START"
+    run_adb "shell $CMD_START"
     ;;
-  x-restart | x-reload)
+  x-restart)
     echo "Restarting Home2l app on $DEV_NAME ..."
-    CMD="shell ($CMD_STOP; $CMD_START)"
+    run_adb "shell ($CMD_STOP; $CMD_START)"
     ;;
+
+  x-install-apk)
+    echo "Installing the Home2l app on $DEV_NAME ..."
+    run_adb "install -r $HOME2L_ROOT/install/Home2lApp.apk"
+    ;;
+  x-install-etc)
+    echo "Updating the Home2l app configuration ('etc') on $DEV_NAME ..."
+    # This procedure requires root permissions for adb (uses su).
+    # Determine root and UID of the APK owner...
+    APK_ROOT=/data/data/org.home2l.app/files
+    APK_STAT_VERSION=(`run_adb "shell stat -t $APK_ROOT/home2l/VERSION" | grep -v '^#'`)
+    APK_UID=${APK_STAT_VERSION[4]}
+      #~ echo "# APK_STAT_VERSION=${APK_STAT_VERSION[*]}"
+      #~ echo "# HOME2L_ROOT=$APK_ROOT HOME2L_UID=$APK_UID"
+    # Create an empty and writable temporary directory ...
+    #   Files pushed in there will be owned by 'shell' and must be removed from here
+    run_adb "root"
+    run_adb "shell rm -fr $APK_ROOT/.update"
+    run_adb "shell su $APK_UID mkdir -p $APK_ROOT/.update"
+    run_adb "shell su $APK_UID chmod 777 $APK_ROOT/.update"
+    # Push (upload) the 'etc' tree ...
+    run_adb "push `realpath /opt/home2l/etc` $APK_ROOT/.update/etc"
+    # Copy the upload into place (this will set the owner properly) ...
+    run_adb "shell su $APK_UID rm -fr $APK_ROOT/home2l/etc"
+    run_adb "shell su $APK_UID cp -r $APK_ROOT/.update/etc $APK_ROOT/home2l/"  2>&1 | grep -v etc/gpio
+    run_adb "shell su $APK_UID chmod -R 700 $APK_ROOT/home2l/etc" 2>&1 | grep -v "No such file or directory"
+    # Cleanup ...
+    run_adb "shell rm -fr $APK_ROOT/.update"
+    run_adb "unroot" || true
+    ;;
+
+  x-ssh)
+    if [[ "$2" == "" ]]; then
+      usage_and_exit
+    fi
+    echo "Checking the SSH configuration on $DEV_NAME ..."
+    echo
+    echo "To allow automatic logins to '$2', add the following line to '~home2l/.ssh/authorized_keys' on '$2':"
+    echo
+    run_adb "shell su root cat /data/data/org.home2l.app/files/home2l/etc/secrets/ssh/$DEV_NAME.pub"
+    echo
+    echo "Running an SSH session from $DEV_NAME to 'home2l@$2' (enter 'exit' to quit) ..."
+    echo
+    run_adb "shell su -c \"ssh -t -i /data/data/org.home2l.app/files/home2l/etc/secrets/ssh/$DEV_NAME -o UserKnownHostsFile=/data/data/org.home2l.app/files/home2l/etc/secrets/ssh/known_hosts -o NoHostAuthenticationForLocalhost=yes home2l@$2\""
+    echo
+    echo "This is the resulting 'known_hosts' file, consider updating your global one accordingly:"
+    echo
+    run_adb "shell su root cat /data/data/org.home2l.app/files/home2l/etc/secrets/ssh/known_hosts"
+    echo
+    ;;
+
+  x-logcat)
+    run_adb "logcat -v time home2l:D SDL:V *:E *:W"
+    ;;
+
   x-connect)
-    CMD="forward tcp:$DEV_PORT tcp:1194"
+    run_adb "forward tcp:$DEV_PORT tcp:1194"
     echo "Connecting $DEV_NAME ($CMD) ..."
     ;;
-  x-logcat)
-    CMD="logcat -v time home2l:D SDL:V *:E *:W"
-    ;;
+
   *)
-    CMD="$@"    # default: pass command from command line
+    run_adb "$@"    # default: pass command from command line
     ;;
 esac
 
-# Invoke ADB with the desired device...
-#~ sg adb -c "adb -s $DEV_ID $CMD"  # does not work
-if [[ "`whoami`" == "home2l" ]]; then
-  adb -s $DEV_ID $CMD | sed 's#^#  [adb] #'
-else
-  sudo -u home2l adb -s $DEV_ID $CMD | sed 's#^#  [adb] #'
-fi
+
+
diff --git a/tools/home2l-install b/tools/home2l-install
--- a/tools/home2l-install
+++ b/tools/home2l-install
@@ -2,7 +2,7 @@
 
 # This file is part of the Home2L project.
 #
-# (C) 2015-2018 Gundolf Kiefer
+# (C) 2015-2020 Gundolf Kiefer
 #
 # Home2L is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,8 +18,8 @@
 # along with Home2L. If not, see <https://www.gnu.org/licenses/>.
 
 
-# This is the working horse to update a Home2L installation on the local host.
-# It requires root priviledges, and it is required that a line like
+# This is the working horse to update a Home2L installation on the local machine.
+# It requires root privileges, and it is required that a line like
 #
 #  "<admin user name> ALL=NOPASSWD:/opt/home2l/bin/home2l-install"
 #
@@ -64,6 +64,7 @@ error () {
 
 SELF=`realpath $0`
 HOME2L_ROOT=${SELF%/bin/*}
+ASK_CONFIRM=1
 
 
 do_init () {
@@ -78,7 +79,11 @@ do_init () {
   echo
   echo "##### Home2L Initialization #####"
   echo
-  echo "About to install:"
+  if [[ $ASK_CONFIRM == 1 ]]; then
+    echo "About to install:"
+  else
+    echo "Installing:"
+  fi
   echo "  $EXEC_LINK/home2l"
   if [[ "$VAR_DIR" != "" ]]; then
     echo "  $VAR_DIR"
@@ -89,22 +94,53 @@ do_init () {
   if [[ "$WITH_INIT" == "1" ]]; then
     echo "  /etc/init.d/home2l - and start the service"
   fi
-  echo
-  read -p "Continue? (y/N) " ANS
-
+  WITH_USER=1
+  if ! id home2l >/dev/null 2>&1; then
+    echo
+    echo "WARNING: No user 'home2l' found in the system."
+    echo "         This may be ok for a demo, but for a productive system, you should"
+    echo "         stop now and add a user account for all Home2L background activities,"
+    echo "         for example (ommit or change the '--pid 5000' clause at your choice):"
+    echo
+    echo "         # adduser --pid 5000 home2l"
+    WITH_USER=0
+  fi
+  if [[ $ASK_CONFIRM == 1 ]]; then
+    echo
+    read -p "Continue? (y/N) " ANS
+  else
+    ANS="y"
+  fi
   if [[ "$ANS" == "y" ]]; then
     rm -f $EXEC_LINK/home2l
     ln -s $HOME2L_ROOT/bin/home2l $EXEC_LINK/home2l
 
     if [[ "$VAR_DIR" != "" ]]; then
       mkdir -p $VAR_DIR
-      chown home2l.home2l $VAR_DIR
+      if [ -e $HOME2L_ROOT/var ]; then
+        if [[ "`realpath -q $HOME2L_ROOT/var`" != "`realpath -q $VAR_DIR`" ]]; then
+          echo "WARNING: '$HOME2L_ROOT/var' already exists and is NOT equivalent to '$VAR_DIR'!"
+        fi
+      else
+        ln -s $VAR_DIR $HOME2L_ROOT/var
+      fi
+      if [[ "$WITH_USER" == "1" ]]; then
+        chown home2l.home2l $VAR_DIR
+      fi
     fi
     if [[ "$TMP_DIR" != "" ]]; then
       mkdir -p $TMP_DIR
-      chown home2l.home2l $TMP_DIR
+      if [ -e $HOME2L_ROOT/tmp ]; then
+        if [[ "`realpath -q $HOME2L_ROOT/tmp`" != "`realpath -q $TMP_DIR`" ]]; then
+          echo "WARNING: '$HOME2L_ROOT/tmp' already exists and is NOT equivalent to '$TMP_DIR'!"
+        fi
+      else
+        ln -s $TMP_DIR $HOME2L_ROOT/tmp
+      fi
+      if [[ "$WITH_USER" == "1" ]]; then
+        chown home2l.home2l $TMP_DIR
+      fi
     fi
-
 
     if [[ "$WITH_INIT" == "1" ]]; then
       cp $HOME2L_ROOT/install/initd-home2l /etc/init.d/home2l
@@ -135,34 +171,12 @@ if [[ "$UID" != "0" ]]; then
 fi
 
 
-# Set environment ...
-HOSTNAME=`hostname`
-if ! which home2l >/dev/null; then
-  do_init
-  exit 0
-fi
-. `home2l -e`
-
-# Load configuration ...
-CONF=$HOME2L_ROOT/etc/install.conf
-test -e $CONF || error "Cannot find configuration file $CONF"
-. $CONF
-
-# Sanity checks ...
-set -e
-if [[ "$HOME2L_ROOT" == "" ]]; then
-  error "HOME2L_ROOT not set properly."
-fi
-if [[ "$HOSTNAME" == "$MASTER" ]]; then
-  error "This tool cannot be run on the master '$MASTER'."
-fi
-
 # Evaluate command line...
 DO_ETC=0
 DO_BLOB=0
 DO_APK=0
-ASK_CONFIRM=1
-SOURCE=$MASTER_URL
+DO_INIT=0
+SOURCE=
 for ARG in $@; do
   case $ARG in
     -e | --etc)
@@ -178,23 +192,54 @@ for ARG in $@; do
       ASK_CONFIRM=0
       ;;
     -i)
-      do_init
-      exit
+      DO_INIT=1
       ;;
     *)
       SOURCE="$ARG"
       ;;
   esac
 done
-if [[ $DO_ETC == 0 && $DO_BLOB == 0 && $DO_APK == 0 ]]; then
+if [[ $DO_ETC == 0 && $DO_BLOB == 0 && $DO_APK == 0 && $DO_INIT == 0 ]]; then
   DO_ETC=1
   DO_BLOB=1
 fi
 if [[ $DO_BLOB == 1 ]]; then
   DO_APK=0
 fi
+
+
+# Init if requested or required ...
+which home2l >/dev/null || DO_INIT=1
+if [[ $DO_INIT == 1 ]]; then
+  do_init
+  exit 0
+fi
+
+
+# Set environment & load configuration ...
+HOSTNAME=`hostname`
+. `home2l -e`
+CONF=$HOME2L_ROOT/etc/install.conf
+test -e $CONF || error "Cannot find configuration file $CONF"
+. $CONF
+
+
+# Complete args ...
 if [[ "$SOURCE" == "" ]]; then
-  error "Source specification is missing."
+  SOURCE=$MASTER_URL
+  if [[ "$SOURCE" == "" ]]; then
+    error "Source specification is missing."
+  fi
+fi
+
+
+# Sanity checks ...
+set -e
+if [[ "$HOME2L_ROOT" == "" ]]; then
+  error "HOME2L_ROOT not set properly."
+fi
+if [[ "$HOSTNAME" == "$MASTER" ]]; then
+  error "This tool cannot be run on the master '$MASTER'."
 fi
 
 
@@ -229,29 +274,9 @@ fi
 
 # Fix ownership & permissions...
 echo
-HAVE_APP=1
-APP_UID=`stat -c %u /data/data/org.home2l.app 2>/dev/null` || HAVE_APP=0
-if [[ $HAVE_APP == 1 ]]; then
-  echo "# Fixing permissions for an Android host ..."
-  chown -R $APP_UID $HOME2L_ROOT/etc/secrets
-  chmod 550 $HOME2L_ROOT/etc/secrets        2>/dev/null || echo "#   (no '$HOME2L_ROOT/etc/secrets' folder found)"
-  chmod 440 $HOME2L_ROOT/etc/secrets/*      2>/dev/null || echo "#   ('$HOME2L_ROOT/etc/secrets' seems to be empty)"
-  chmod 500 $HOME2L_ROOT/etc/secrets/ssh    2>/dev/null || echo "#   (no '$HOME2L_ROOT/etc/secrets/ssh' folder found)"
-  chmod 400 $HOME2L_ROOT/etc/secrets/ssh/*  2>/dev/null || echo "#   ('$HOME2L_ROOT/etc/secrets/ssh/' seems to be empty)"
-  mkdir -p $HOME2L_ROOT/var $HOME2L_ROOT/tmp
-  chmod 2777  $HOME2L_ROOT/var $HOME2L_ROOT/tmp
-else
-  echo "# Fixing permissions for a Non-Android host ..."
-  chmod 550 $HOME2L_ROOT/etc/secrets    2>/dev/null || echo "#   (no '$HOME2L_ROOT/etc/secrets' folder found)"
-  chmod 440 $HOME2L_ROOT/etc/secrets/*  2>/dev/null || echo "#   ('$HOME2L_ROOT/etc/secrets' seems to be empty)"
-fi
-if [[ $HAVE_APP == 0 && $HOME2L_ROOT == /data/home2l ]]; then
-  echo
-  echo "WARNING: According to HOME2L_ROOT, this seems to be an Android machine."
-  echo "  However, I could not find the Home2l App. You should now install"
-  echo "  the app and must then run this script again. Otherwise, the app may"
-  echo "  not work properly."
-fi
+echo "# Fixing permissions ..."
+chmod 440 `find /opt/home2l/etc/secrets -type f` $HOME2L_ROOT/etc/secrets 2>/dev/null || echo "#   (no files found in '$HOME2L_ROOT/etc/secrets')"
+chmod 550 `find /opt/home2l/etc/secrets -type d` $HOME2L_ROOT/etc/secrets 2>/dev/null || echo "#   ('$HOME2L_ROOT/etc/secrets' not found)"
 
 
 # Restart daemon (if active) and other house-keeping...
@@ -264,6 +289,7 @@ if [[ $DO_BLOB == 1 || $DO_ETC == 1 ]]; then
     service home2l status && service home2l reload
   fi
 fi
+
 
 # Exit successfully...
 exit 0
